//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTracker.FlightTrackerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://www.steveives.com")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airline> AirlinesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airline> Airlines {
            get {
                return this.AirlinesField;
            }
            set {
                if ((object.ReferenceEquals(this.AirlinesField, value) != true)) {
                    this.AirlinesField = value;
                    this.RaisePropertyChanged("Airlines");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Airline", Namespace="http://www.steveives.com")]
    [System.SerializableAttribute()]
    public partial class Airline : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcaoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallSignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightPrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightTracker.FlightTrackerService.Country CountryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IcaoCode {
            get {
                return this.IcaoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IcaoCodeField, value) != true)) {
                    this.IcaoCodeField = value;
                    this.RaisePropertyChanged("IcaoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CallSign {
            get {
                return this.CallSignField;
            }
            set {
                if ((object.ReferenceEquals(this.CallSignField, value) != true)) {
                    this.CallSignField = value;
                    this.RaisePropertyChanged("CallSign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FlightPrefix {
            get {
                return this.FlightPrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightPrefixField, value) != true)) {
                    this.FlightPrefixField = value;
                    this.RaisePropertyChanged("FlightPrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WebSite {
            get {
                return this.WebSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebSiteField, value) != true)) {
                    this.WebSiteField = value;
                    this.RaisePropertyChanged("WebSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FlightTracker.FlightTrackerService.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Airport", Namespace="http://www.steveives.com")]
    [System.SerializableAttribute()]
    public partial class Airport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AirportCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FlightTracker.FlightTrackerService.Country CountryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AirportCode {
            get {
                return this.AirportCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AirportCodeField, value) != true)) {
                    this.AirportCodeField = value;
                    this.RaisePropertyChanged("AirportCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WebSite {
            get {
                return this.WebSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebSiteField, value) != true)) {
                    this.WebSiteField = value;
                    this.RaisePropertyChanged("WebSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public FlightTracker.FlightTrackerService.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.steveives.com", ConfigurationName="FlightTrackerService.FlightTrackerServiceSoap")]
    public interface FlightTrackerServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://www.steveives.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.steveives.com/HelloWorld", ReplyAction="*")]
        FlightTracker.FlightTrackerService.HelloWorldResponse HelloWorld(FlightTracker.FlightTrackerService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.steveives.com/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(FlightTracker.FlightTrackerService.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        FlightTracker.FlightTrackerService.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name GetCountriesResult from namespace http://www.steveives.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.steveives.com/GetCountries", ReplyAction="*")]
        FlightTracker.FlightTrackerService.GetCountriesResponse GetCountries(FlightTracker.FlightTrackerService.GetCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.steveives.com/GetCountries", ReplyAction="*")]
        System.IAsyncResult BeginGetCountries(FlightTracker.FlightTrackerService.GetCountriesRequest request, System.AsyncCallback callback, object asyncState);
        
        FlightTracker.FlightTrackerService.GetCountriesResponse EndGetCountries(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name GetAirportsResult from namespace http://www.steveives.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.steveives.com/GetAirports", ReplyAction="*")]
        FlightTracker.FlightTrackerService.GetAirportsResponse GetAirports(FlightTracker.FlightTrackerService.GetAirportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.steveives.com/GetAirports", ReplyAction="*")]
        System.IAsyncResult BeginGetAirports(FlightTracker.FlightTrackerService.GetAirportsRequest request, System.AsyncCallback callback, object asyncState);
        
        FlightTracker.FlightTrackerService.GetAirportsResponse EndGetAirports(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name GetAirlinesResult from namespace http://www.steveives.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.steveives.com/GetAirlines", ReplyAction="*")]
        FlightTracker.FlightTrackerService.GetAirlinesResponse GetAirlines(FlightTracker.FlightTrackerService.GetAirlinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.steveives.com/GetAirlines", ReplyAction="*")]
        System.IAsyncResult BeginGetAirlines(FlightTracker.FlightTrackerService.GetAirlinesRequest request, System.AsyncCallback callback, object asyncState);
        
        FlightTracker.FlightTrackerService.GetAirlinesResponse EndGetAirlines(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.steveives.com", Order=0)]
        public FlightTracker.FlightTrackerService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(FlightTracker.FlightTrackerService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.steveives.com", Order=0)]
        public FlightTracker.FlightTrackerService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(FlightTracker.FlightTrackerService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.steveives.com")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountries", Namespace="http://www.steveives.com", Order=0)]
        public FlightTracker.FlightTrackerService.GetCountriesRequestBody Body;
        
        public GetCountriesRequest() {
        }
        
        public GetCountriesRequest(FlightTracker.FlightTrackerService.GetCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCountriesRequestBody {
        
        public GetCountriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesResponse", Namespace="http://www.steveives.com", Order=0)]
        public FlightTracker.FlightTrackerService.GetCountriesResponseBody Body;
        
        public GetCountriesResponse() {
        }
        
        public GetCountriesResponse(FlightTracker.FlightTrackerService.GetCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.steveives.com")]
    public partial class GetCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Country> GetCountriesResult;
        
        public GetCountriesResponseBody() {
        }
        
        public GetCountriesResponseBody(System.Collections.Generic.List<FlightTracker.FlightTrackerService.Country> GetCountriesResult) {
            this.GetCountriesResult = GetCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAirportsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAirports", Namespace="http://www.steveives.com", Order=0)]
        public FlightTracker.FlightTrackerService.GetAirportsRequestBody Body;
        
        public GetAirportsRequest() {
        }
        
        public GetAirportsRequest(FlightTracker.FlightTrackerService.GetAirportsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAirportsRequestBody {
        
        public GetAirportsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAirportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAirportsResponse", Namespace="http://www.steveives.com", Order=0)]
        public FlightTracker.FlightTrackerService.GetAirportsResponseBody Body;
        
        public GetAirportsResponse() {
        }
        
        public GetAirportsResponse(FlightTracker.FlightTrackerService.GetAirportsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.steveives.com")]
    public partial class GetAirportsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airport> GetAirportsResult;
        
        public GetAirportsResponseBody() {
        }
        
        public GetAirportsResponseBody(System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airport> GetAirportsResult) {
            this.GetAirportsResult = GetAirportsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAirlinesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAirlines", Namespace="http://www.steveives.com", Order=0)]
        public FlightTracker.FlightTrackerService.GetAirlinesRequestBody Body;
        
        public GetAirlinesRequest() {
        }
        
        public GetAirlinesRequest(FlightTracker.FlightTrackerService.GetAirlinesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAirlinesRequestBody {
        
        public GetAirlinesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAirlinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAirlinesResponse", Namespace="http://www.steveives.com", Order=0)]
        public FlightTracker.FlightTrackerService.GetAirlinesResponseBody Body;
        
        public GetAirlinesResponse() {
        }
        
        public GetAirlinesResponse(FlightTracker.FlightTrackerService.GetAirlinesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.steveives.com")]
    public partial class GetAirlinesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airline> GetAirlinesResult;
        
        public GetAirlinesResponseBody() {
        }
        
        public GetAirlinesResponseBody(System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airline> GetAirlinesResult) {
            this.GetAirlinesResult = GetAirlinesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlightTrackerServiceSoapChannel : FlightTracker.FlightTrackerService.FlightTrackerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Country> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<FlightTracker.FlightTrackerService.Country>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAirportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAirportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airport> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airport>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAirlinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAirlinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airline> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airline>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlightTrackerServiceSoapClient : System.ServiceModel.ClientBase<FlightTracker.FlightTrackerService.FlightTrackerServiceSoap>, FlightTracker.FlightTrackerService.FlightTrackerServiceSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCountriesDelegate;
        
        private EndOperationDelegate onEndGetCountriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetCountriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAirportsDelegate;
        
        private EndOperationDelegate onEndGetAirportsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAirportsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAirlinesDelegate;
        
        private EndOperationDelegate onEndGetAirlinesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAirlinesCompletedDelegate;
        
        public FlightTrackerServiceSoapClient() {
        }
        
        public FlightTrackerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlightTrackerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightTrackerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightTrackerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<GetCountriesCompletedEventArgs> GetCountriesCompleted;
        
        public event System.EventHandler<GetAirportsCompletedEventArgs> GetAirportsCompleted;
        
        public event System.EventHandler<GetAirlinesCompletedEventArgs> GetAirlinesCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightTracker.FlightTrackerService.HelloWorldResponse FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.HelloWorld(FlightTracker.FlightTrackerService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            FlightTracker.FlightTrackerService.HelloWorldRequest inValue = new FlightTracker.FlightTrackerService.HelloWorldRequest();
            inValue.Body = new FlightTracker.FlightTrackerService.HelloWorldRequestBody();
            FlightTracker.FlightTrackerService.HelloWorldResponse retVal = ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.BeginHelloWorld(FlightTracker.FlightTrackerService.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            FlightTracker.FlightTrackerService.HelloWorldRequest inValue = new FlightTracker.FlightTrackerService.HelloWorldRequest();
            inValue.Body = new FlightTracker.FlightTrackerService.HelloWorldRequestBody();
            return ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightTracker.FlightTrackerService.HelloWorldResponse FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHelloWorld(System.IAsyncResult result) {
            FlightTracker.FlightTrackerService.HelloWorldResponse retVal = ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightTracker.FlightTrackerService.GetCountriesResponse FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.GetCountries(FlightTracker.FlightTrackerService.GetCountriesRequest request) {
            return base.Channel.GetCountries(request);
        }
        
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Country> GetCountries() {
            FlightTracker.FlightTrackerService.GetCountriesRequest inValue = new FlightTracker.FlightTrackerService.GetCountriesRequest();
            inValue.Body = new FlightTracker.FlightTrackerService.GetCountriesRequestBody();
            FlightTracker.FlightTrackerService.GetCountriesResponse retVal = ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).GetCountries(inValue);
            return retVal.Body.GetCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.BeginGetCountries(FlightTracker.FlightTrackerService.GetCountriesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCountries(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCountries(System.AsyncCallback callback, object asyncState) {
            FlightTracker.FlightTrackerService.GetCountriesRequest inValue = new FlightTracker.FlightTrackerService.GetCountriesRequest();
            inValue.Body = new FlightTracker.FlightTrackerService.GetCountriesRequestBody();
            return ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).BeginGetCountries(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightTracker.FlightTrackerService.GetCountriesResponse FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.EndGetCountries(System.IAsyncResult result) {
            return base.Channel.EndGetCountries(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Country> EndGetCountries(System.IAsyncResult result) {
            FlightTracker.FlightTrackerService.GetCountriesResponse retVal = ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).EndGetCountries(result);
            return retVal.Body.GetCountriesResult;
        }
        
        private System.IAsyncResult OnBeginGetCountries(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetCountries(callback, asyncState);
        }
        
        private object[] OnEndGetCountries(System.IAsyncResult result) {
            System.Collections.Generic.List<FlightTracker.FlightTrackerService.Country> retVal = this.EndGetCountries(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCountriesCompleted(object state) {
            if ((this.GetCountriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCountriesCompleted(this, new GetCountriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCountriesAsync() {
            this.GetCountriesAsync(null);
        }
        
        public void GetCountriesAsync(object userState) {
            if ((this.onBeginGetCountriesDelegate == null)) {
                this.onBeginGetCountriesDelegate = new BeginOperationDelegate(this.OnBeginGetCountries);
            }
            if ((this.onEndGetCountriesDelegate == null)) {
                this.onEndGetCountriesDelegate = new EndOperationDelegate(this.OnEndGetCountries);
            }
            if ((this.onGetCountriesCompletedDelegate == null)) {
                this.onGetCountriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCountriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCountriesDelegate, null, this.onEndGetCountriesDelegate, this.onGetCountriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightTracker.FlightTrackerService.GetAirportsResponse FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.GetAirports(FlightTracker.FlightTrackerService.GetAirportsRequest request) {
            return base.Channel.GetAirports(request);
        }
        
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airport> GetAirports() {
            FlightTracker.FlightTrackerService.GetAirportsRequest inValue = new FlightTracker.FlightTrackerService.GetAirportsRequest();
            inValue.Body = new FlightTracker.FlightTrackerService.GetAirportsRequestBody();
            FlightTracker.FlightTrackerService.GetAirportsResponse retVal = ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).GetAirports(inValue);
            return retVal.Body.GetAirportsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.BeginGetAirports(FlightTracker.FlightTrackerService.GetAirportsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAirports(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAirports(System.AsyncCallback callback, object asyncState) {
            FlightTracker.FlightTrackerService.GetAirportsRequest inValue = new FlightTracker.FlightTrackerService.GetAirportsRequest();
            inValue.Body = new FlightTracker.FlightTrackerService.GetAirportsRequestBody();
            return ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).BeginGetAirports(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightTracker.FlightTrackerService.GetAirportsResponse FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.EndGetAirports(System.IAsyncResult result) {
            return base.Channel.EndGetAirports(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airport> EndGetAirports(System.IAsyncResult result) {
            FlightTracker.FlightTrackerService.GetAirportsResponse retVal = ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).EndGetAirports(result);
            return retVal.Body.GetAirportsResult;
        }
        
        private System.IAsyncResult OnBeginGetAirports(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAirports(callback, asyncState);
        }
        
        private object[] OnEndGetAirports(System.IAsyncResult result) {
            System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airport> retVal = this.EndGetAirports(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAirportsCompleted(object state) {
            if ((this.GetAirportsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAirportsCompleted(this, new GetAirportsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAirportsAsync() {
            this.GetAirportsAsync(null);
        }
        
        public void GetAirportsAsync(object userState) {
            if ((this.onBeginGetAirportsDelegate == null)) {
                this.onBeginGetAirportsDelegate = new BeginOperationDelegate(this.OnBeginGetAirports);
            }
            if ((this.onEndGetAirportsDelegate == null)) {
                this.onEndGetAirportsDelegate = new EndOperationDelegate(this.OnEndGetAirports);
            }
            if ((this.onGetAirportsCompletedDelegate == null)) {
                this.onGetAirportsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAirportsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAirportsDelegate, null, this.onEndGetAirportsDelegate, this.onGetAirportsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightTracker.FlightTrackerService.GetAirlinesResponse FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.GetAirlines(FlightTracker.FlightTrackerService.GetAirlinesRequest request) {
            return base.Channel.GetAirlines(request);
        }
        
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airline> GetAirlines() {
            FlightTracker.FlightTrackerService.GetAirlinesRequest inValue = new FlightTracker.FlightTrackerService.GetAirlinesRequest();
            inValue.Body = new FlightTracker.FlightTrackerService.GetAirlinesRequestBody();
            FlightTracker.FlightTrackerService.GetAirlinesResponse retVal = ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).GetAirlines(inValue);
            return retVal.Body.GetAirlinesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.BeginGetAirlines(FlightTracker.FlightTrackerService.GetAirlinesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAirlines(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAirlines(System.AsyncCallback callback, object asyncState) {
            FlightTracker.FlightTrackerService.GetAirlinesRequest inValue = new FlightTracker.FlightTrackerService.GetAirlinesRequest();
            inValue.Body = new FlightTracker.FlightTrackerService.GetAirlinesRequestBody();
            return ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).BeginGetAirlines(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightTracker.FlightTrackerService.GetAirlinesResponse FlightTracker.FlightTrackerService.FlightTrackerServiceSoap.EndGetAirlines(System.IAsyncResult result) {
            return base.Channel.EndGetAirlines(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airline> EndGetAirlines(System.IAsyncResult result) {
            FlightTracker.FlightTrackerService.GetAirlinesResponse retVal = ((FlightTracker.FlightTrackerService.FlightTrackerServiceSoap)(this)).EndGetAirlines(result);
            return retVal.Body.GetAirlinesResult;
        }
        
        private System.IAsyncResult OnBeginGetAirlines(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAirlines(callback, asyncState);
        }
        
        private object[] OnEndGetAirlines(System.IAsyncResult result) {
            System.Collections.Generic.List<FlightTracker.FlightTrackerService.Airline> retVal = this.EndGetAirlines(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAirlinesCompleted(object state) {
            if ((this.GetAirlinesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAirlinesCompleted(this, new GetAirlinesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAirlinesAsync() {
            this.GetAirlinesAsync(null);
        }
        
        public void GetAirlinesAsync(object userState) {
            if ((this.onBeginGetAirlinesDelegate == null)) {
                this.onBeginGetAirlinesDelegate = new BeginOperationDelegate(this.OnBeginGetAirlines);
            }
            if ((this.onEndGetAirlinesDelegate == null)) {
                this.onEndGetAirlinesDelegate = new EndOperationDelegate(this.OnEndGetAirlines);
            }
            if ((this.onGetAirlinesCompletedDelegate == null)) {
                this.onGetAirlinesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAirlinesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAirlinesDelegate, null, this.onEndGetAirlinesDelegate, this.onGetAirlinesCompletedDelegate, userState);
        }
    }
}
