//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 10/13/2010 9:06:06 PM
namespace MainApp.StocksDataService
{
    
    /// <summary>
    /// There are no comments for StocksData in the schema.
    /// </summary>
    public partial class StocksData : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new StocksData object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public StocksData(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("CLRData", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("MainApp.StocksDataService", typeName.Substring(7)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("MainApp.StocksDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("CLRData.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Stocks in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Stock> Stocks
        {
            get
            {
                if ((this._Stocks == null))
                {
                    this._Stocks = base.CreateQuery<Stock>("Stocks");
                }
                return this._Stocks;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Stock> _Stocks;
        /// <summary>
        /// There are no comments for Quotes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Quote> Quotes
        {
            get
            {
                if ((this._Quotes == null))
                {
                    this._Quotes = base.CreateQuery<Quote>("Quotes");
                }
                return this._Quotes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Quote> _Quotes;
        /// <summary>
        /// There are no comments for Stocks in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStocks(Stock stock)
        {
            base.AddObject("Stocks", stock);
        }
        /// <summary>
        /// There are no comments for Quotes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToQuotes(Quote quote)
        {
            base.AddObject("Quotes", quote);
        }
    }
    /// <summary>
    /// There are no comments for CLRData.Stock in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Stocks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Stock : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Stock object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Stock CreateStock(string ID)
        {
            Stock stock = new Stock();
            stock.Id = ID;
            return stock;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Quotes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Quote> Quotes
        {
            get
            {
                return this._Quotes;
            }
            set
            {
                this._Quotes = value;
                this.OnPropertyChanged("Quotes");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Quote> _Quotes = new global::System.Data.Services.Client.DataServiceCollection<Quote>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CLRData.Quote in the schema.
    /// </summary>
    /// <KeyProperties>
    /// StockId
    /// Timestamp
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Quotes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("StockId", "Timestamp")]
    public partial class Quote : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Quote object.
        /// </summary>
        /// <param name="stockId">Initial value of StockId.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        /// <param name="buy">Initial value of Buy.</param>
        /// <param name="sell">Initial value of Sell.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Quote CreateQuote(string stockId, long timestamp, double buy, double sell)
        {
            Quote quote = new Quote();
            quote.StockId = stockId;
            quote.Timestamp = timestamp;
            quote.Buy = buy;
            quote.Sell = sell;
            return quote;
        }
        /// <summary>
        /// There are no comments for Property StockId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StockId
        {
            get
            {
                return this._StockId;
            }
            set
            {
                this.OnStockIdChanging(value);
                this._StockId = value;
                this.OnStockIdChanged();
                this.OnPropertyChanged("StockId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StockId;
        partial void OnStockIdChanging(string value);
        partial void OnStockIdChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Timestamp
        {
            get
            {
                return this._Timestamp;
            }
            set
            {
                this.OnTimestampChanging(value);
                this._Timestamp = value;
                this.OnTimestampChanged();
                this.OnPropertyChanged("Timestamp");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Timestamp;
        partial void OnTimestampChanging(long value);
        partial void OnTimestampChanged();
        /// <summary>
        /// There are no comments for Property Buy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Buy
        {
            get
            {
                return this._Buy;
            }
            set
            {
                this.OnBuyChanging(value);
                this._Buy = value;
                this.OnBuyChanged();
                this.OnPropertyChanged("Buy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Buy;
        partial void OnBuyChanging(double value);
        partial void OnBuyChanged();
        /// <summary>
        /// There are no comments for Property Sell in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Sell
        {
            get
            {
                return this._Sell;
            }
            set
            {
                this.OnSellChanging(value);
                this._Sell = value;
                this.OnSellChanged();
                this.OnPropertyChanged("Sell");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Sell;
        partial void OnSellChanging(double value);
        partial void OnSellChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
