/*
 * MainForm.java
 *
 * Created on June 30, 2005, 12:03 PM
 */

package appdemo;
import java.util.ArrayList;

/**
 *
 * @author  stevei
 */
public class MainForm extends javax.swing.JFrame {
    
    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuTools = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo xfNetLink Java Client");
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10));
        setLocationByPlatform(true);
        setName("MainFrame");
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 420));

        jMenuFile.setText("File");
        jMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileActionPerformed(evt);
            }
        });

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });

        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuBar1.add(jMenuEdit);

        jMenuTools.setText("Tools");
        jMenuBar1.add(jMenuTools);

        jMenuHelp.setText("Help");
        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
// TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItemExitActionPerformed
    
    private void jMenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuFileActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                
                //Process login dialog
                LoginPanel lp = new LoginPanel();
                lp.setVisible(true);
                
                //Define work variables
                boolean ok = true;
                int sts;
                StringBuffer ErrorText= new StringBuffer();
                xfpldemo.utils synergy = new xfpldemo.utils();
                ArrayList ProductGroups = null;
                xfpldemo.User CurrentUser = null;
                xfpldemo.Customer CurrentCustomer = null;
                
                //Define data which will be cached
                try {
                    CurrentUser = new xfpldemo.User();
                    CurrentCustomer = new xfpldemo.Customer();
                } catch (Exception e) {
                    ok=false;
                }
                
                if (ok) {
                    //Get ready to connect
                    synergy.setxfHost("localhost");
                    synergy.setxfPort(2356);
                    
                    //Connect
                    try {
                        synergy.connect();
                    } catch (Exception e) {
                        ok=false;
                    }
                }
                
                
                if (ok) {
                    //Setup the server-side environment
                    try {
                        sts = synergy.Initialize();
                        if (sts!=0) {
                            ok=false;
                        }
                    } catch (Exception e) {
                        ok=false;
                    }
                }
                
                
                if (ok) {
                    //Server is ready, call the login method
                    String username = "steve";
                    String password = "ives";
                    try {
                        sts = synergy.login(username,password,ErrorText,CurrentUser);
                        if (sts!=0) {
                            ok=false;
                        }
                    } catch (Exception e) {
                        ok=false;
                    }
                }
                
                if (ok) {
                    //We're logged in, retrieve the customer record
                    try {
                        CurrentCustomer.setAccount(CurrentUser.getCustomer());
                        sts = synergy.get_customer(CurrentCustomer,ErrorText);
                        if (sts!=0) {
                            ok=false;
                        }
                    } catch (Exception e) {
                        ok=false;
                    }
                }
                
                if (ok) {
                    //Retrieve product groups
                    try {
                        ProductGroups = new ArrayList();
                        synergy.get_product_groups_arraylist(ProductGroups);
                    } catch (Exception e) {
                        ok=false;
                    }
                }
                
                if (ok) {
                    try {
                        synergy.disconnect();
                    } catch (Exception e) {
                        ok=false;
                    }
                }
                
                
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
