<CODEGEN_FILENAME><structure_name>_map.dbl</CODEGEN_FILENAME>
;//*****************************************************************************
;//
;// Title:        sql_map.tpl
;//
;// Description:  Template to generate a Synergy subroutine which maps fields in
;//               one record to corresponding fields in another record.  This
;//               template requires that you use an @MAP=STRUCTURE; declaration
;//               in the target structures user text field, and an @MAP=FIELD;
;//               declaration in each of the target structure fields user text
;//               fields.
;//
;// Author:       Steve Ives, Synergex Professional Services Group
;//
;// Copyright:    ©Synergex International Inc.  All rights reserved.
;//
;// WARNING:      If you were given this code by a Synergex employee then you
;//               may use and modify it freely to generate code for your
;//               applications. However, you may not under any circumstances
;//               distribute this code, or any modified version of this code,
;//               to any third party without first obtaining written permission
;//               to do so from Synergex. In using this code you accept that it
;//               is provided as is, and without support or warranty. Neither
;//               Synergex or the author accept any responsibility for any
;//               losses or damages of any nature which may arise from the use
;//               of this code. This header information must remain unaltered
;//               in the code at all times. Possession of this code, or any
;//               modified version of this code, indicates your acceptance of
;//               these terms.
;//
;;*****************************************************************************
;;
;; Routine:     <structure_name>_map
;;
;; Author:      <AUTHOR>
;;
;; Company:     <COMPANY>
;;
;;*****************************************************************************
;;
;; WARNING:     This code was generated by CodeGen. Any changes that you make
;;              to this file will be lost if the code is regenerated.
;;
;; This code is supplied as seen and without warranty or support, and is used
;; at your own risk. Neither the author or Synergex accept any responsability
;; for any loss or damage which may result from the use of this code. This text
;; must remain unaltered in this file at all times. Possession or use of this
;; code, or any modified version of this code, indicates your acceptance of
;; these conditions.
;;
;;*****************************************************************************
;;
.include "<MAPPED_STRUCTURE>" repository, structure="str<MAPPED_STRUCTURE>", end
.include "<STRUCTURE_NOALIAS>" repository, structure="str<STRUCTURE_NAME>", end

subroutine <structure_name>_map

    required in  <mapped_structure> ,str<MAPPED_STRUCTURE>
    required out <structure_name>        ,str<STRUCTURE_NAME>
    endparams

proc

    ;;Store the record
    <FIELD_LOOP>
    <field_path> = <mapped_path_conv>
    </FIELD_LOOP>

    xreturn

endsubroutine
