//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace webServiceClientApp.spc2010 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SPC2010WebServiceSoap", Namespace="http://psg.synergex.com/")]
    public partial class SPC2010WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerContactsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerAddressesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContactForUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateContactOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SPC2010WebService() {
            this.Url = global::webServiceClientApp.Properties.Settings.Default.webServiceClientApp_spc2010_SPC2010WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCustomersCompletedEventHandler GetCustomersCompleted;
        
        /// <remarks/>
        public event GetCustomerContactsCompletedEventHandler GetCustomerContactsCompleted;
        
        /// <remarks/>
        public event GetCustomerAddressesCompletedEventHandler GetCustomerAddressesCompleted;
        
        /// <remarks/>
        public event GetContactForUpdateCompletedEventHandler GetContactForUpdateCompleted;
        
        /// <remarks/>
        public event UpdateContactCompletedEventHandler UpdateContactCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://psg.synergex.com/GetCustomers", RequestNamespace="http://psg.synergex.com/", ResponseNamespace="http://psg.synergex.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Customer[] GetCustomers() {
            object[] results = this.Invoke("GetCustomers", new object[0]);
            return ((Customer[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomersAsync() {
            this.GetCustomersAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomersAsync(object userState) {
            if ((this.GetCustomersOperationCompleted == null)) {
                this.GetCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomersOperationCompleted);
            }
            this.InvokeAsync("GetCustomers", new object[0], this.GetCustomersOperationCompleted, userState);
        }
        
        private void OnGetCustomersOperationCompleted(object arg) {
            if ((this.GetCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://psg.synergex.com/GetCustomerContacts", RequestNamespace="http://psg.synergex.com/", ResponseNamespace="http://psg.synergex.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Contact[] GetCustomerContacts(int customerId) {
            object[] results = this.Invoke("GetCustomerContacts", new object[] {
                        customerId});
            return ((Contact[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerContactsAsync(int customerId) {
            this.GetCustomerContactsAsync(customerId, null);
        }
        
        /// <remarks/>
        public void GetCustomerContactsAsync(int customerId, object userState) {
            if ((this.GetCustomerContactsOperationCompleted == null)) {
                this.GetCustomerContactsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerContactsOperationCompleted);
            }
            this.InvokeAsync("GetCustomerContacts", new object[] {
                        customerId}, this.GetCustomerContactsOperationCompleted, userState);
        }
        
        private void OnGetCustomerContactsOperationCompleted(object arg) {
            if ((this.GetCustomerContactsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerContactsCompleted(this, new GetCustomerContactsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://psg.synergex.com/GetCustomerAddresses", RequestNamespace="http://psg.synergex.com/", ResponseNamespace="http://psg.synergex.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Address[] GetCustomerAddresses(int customerId) {
            object[] results = this.Invoke("GetCustomerAddresses", new object[] {
                        customerId});
            return ((Address[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerAddressesAsync(int customerId) {
            this.GetCustomerAddressesAsync(customerId, null);
        }
        
        /// <remarks/>
        public void GetCustomerAddressesAsync(int customerId, object userState) {
            if ((this.GetCustomerAddressesOperationCompleted == null)) {
                this.GetCustomerAddressesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerAddressesOperationCompleted);
            }
            this.InvokeAsync("GetCustomerAddresses", new object[] {
                        customerId}, this.GetCustomerAddressesOperationCompleted, userState);
        }
        
        private void OnGetCustomerAddressesOperationCompleted(object arg) {
            if ((this.GetCustomerAddressesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerAddressesCompleted(this, new GetCustomerAddressesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://psg.synergex.com/GetContactForUpdate", RequestNamespace="http://psg.synergex.com/", ResponseNamespace="http://psg.synergex.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Method_status GetContactForUpdate(int customerId, int contactId, out Contact contact, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] out byte[] grfa, out string msg) {
            object[] results = this.Invoke("GetContactForUpdate", new object[] {
                        customerId,
                        contactId});
            contact = ((Contact)(results[1]));
            grfa = ((byte[])(results[2]));
            msg = ((string)(results[3]));
            return ((Method_status)(results[0]));
        }
        
        /// <remarks/>
        public void GetContactForUpdateAsync(int customerId, int contactId) {
            this.GetContactForUpdateAsync(customerId, contactId, null);
        }
        
        /// <remarks/>
        public void GetContactForUpdateAsync(int customerId, int contactId, object userState) {
            if ((this.GetContactForUpdateOperationCompleted == null)) {
                this.GetContactForUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContactForUpdateOperationCompleted);
            }
            this.InvokeAsync("GetContactForUpdate", new object[] {
                        customerId,
                        contactId}, this.GetContactForUpdateOperationCompleted, userState);
        }
        
        private void OnGetContactForUpdateOperationCompleted(object arg) {
            if ((this.GetContactForUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContactForUpdateCompleted(this, new GetContactForUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://psg.synergex.com/UpdateContact", RequestNamespace="http://psg.synergex.com/", ResponseNamespace="http://psg.synergex.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Method_status UpdateContact(ref Contact contact, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] ref byte[] grfa, out string msg) {
            object[] results = this.Invoke("UpdateContact", new object[] {
                        contact,
                        grfa});
            contact = ((Contact)(results[1]));
            grfa = ((byte[])(results[2]));
            msg = ((string)(results[3]));
            return ((Method_status)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateContactAsync(Contact contact, byte[] grfa) {
            this.UpdateContactAsync(contact, grfa, null);
        }
        
        /// <remarks/>
        public void UpdateContactAsync(Contact contact, byte[] grfa, object userState) {
            if ((this.UpdateContactOperationCompleted == null)) {
                this.UpdateContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateContactOperationCompleted);
            }
            this.InvokeAsync("UpdateContact", new object[] {
                        contact,
                        grfa}, this.UpdateContactOperationCompleted, userState);
        }
        
        private void OnUpdateContactOperationCompleted(object arg) {
            if ((this.UpdateContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateContactCompleted(this, new UpdateContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psg.synergex.com/")]
    public partial class Customer {
        
        private int customerIdField;
        
        private string customerNameField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateModifiedField;
        
        private string statusField;
        
        /// <remarks/>
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psg.synergex.com/")]
    public partial class Address {
        
        private int customerIdField;
        
        private int addressIdField;
        
        private string addressTypeField;
        
        private string streetField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        /// <remarks/>
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public int AddressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
            }
        }
        
        /// <remarks/>
        public string AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psg.synergex.com/")]
    public partial class Contact {
        
        private int customerIdField;
        
        private int contactIdField;
        
        private string salutationField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string friendlyNameField;
        
        private string workPhoneField;
        
        private string homePhoneField;
        
        private string emailField;
        
        private string departmentField;
        
        private string titleField;
        
        /// <remarks/>
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public int ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FriendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psg.synergex.com/")]
    public enum Method_status {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Info_error,
        
        /// <remarks/>
        Fatal_error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCustomersCompletedEventHandler(object sender, GetCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCustomerContactsCompletedEventHandler(object sender, GetCustomerContactsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerContactsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerContactsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Contact[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Contact[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCustomerAddressesCompletedEventHandler(object sender, GetCustomerAddressesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerAddressesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerAddressesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Address[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Address[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetContactForUpdateCompletedEventHandler(object sender, GetContactForUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContactForUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContactForUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Method_status Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Method_status)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Contact contact {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Contact)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public byte[] grfa {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateContactCompletedEventHandler(object sender, UpdateContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Method_status Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Method_status)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Contact contact {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Contact)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public byte[] grfa {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
}

#pragma warning restore 1591