dbl -dXTo OBJ: SUB:appclose
dbl -dXTo OBJ: SUB:appresize
dbl -dXTo OBJ: SUB:helpmethod
dbl -dXTo OBJ: SUB:itemselected
dbl -dXTo OBJ: SUB:loadlistitems
dbl -dXTo OBJ: SUB:shutdown
dbl -dXTo OBJ: SUB:startup
dbl -dXTo OBJ: SUB:switchlistmode
dbl -dXTo OBJ: SUB:utilmethod
dblibr -r OBJ:psgmenu.olb OBJ:appclose
dblibr -r OBJ:psgmenu.olb OBJ:appresize
dblibr -r OBJ:psgmenu.olb OBJ:helpmethod
dblibr -r OBJ:psgmenu.olb OBJ:itemselected
dblibr -r OBJ:psgmenu.olb OBJ:loadlistitems
dblibr -r OBJ:psgmenu.olb OBJ:shutdown
dblibr -r OBJ:psgmenu.olb OBJ:startup
dblibr -r OBJ:psgmenu.olb OBJ:switchlistmode
dblibr -r OBJ:psgmenu.olb OBJ:utilmethod
dblink -ld EXE:psgmenu.elb OBJ:psgmenu.olb
dbl -dXTo OBJ: SRC:psgmenu
dblink -do EXE: OBJ:psgmenu EXE:psgmenu.elb WND:tklib.elb DBLDIR:axlib.elb RPSLIB:ddlib.elb
