'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
'
Namespace webserver
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="GalleryServiceSoap", [Namespace]:="http://communityserver.org/gallery/services/posts/")>  _
    Partial Public Class GalleryService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private serviceCredentialsValueField As ServiceCredentials
        
        Private CreateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCategoriesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetAlbumHeirarchyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GalleriesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPicturesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPictureOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetAlbumPicturesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSupportedFileExtensionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ValidateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CommunityClient.My.MySettings.Default.CommunityClient_webserver_GalleryService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property ServiceCredentialsValue() As ServiceCredentials
            Get
                Return Me.serviceCredentialsValueField
            End Get
            Set
                Me.serviceCredentialsValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreateCompleted As CreateCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCompleted As UpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteCompleted As DeleteCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCategoriesCompleted As GetCategoriesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetAlbumHeirarchyCompleted As GetAlbumHeirarchyCompletedEventHandler
        
        '''<remarks/>
        Public Event GalleriesCompleted As GalleriesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPicturesCompleted As GetPicturesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPictureCompleted As GetPictureCompletedEventHandler
        
        '''<remarks/>
        Public Event GetAlbumPicturesCompleted As GetAlbumPicturesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSupportedFileExtensionsCompleted As GetSupportedFileExtensionsCompletedEventHandler
        
        '''<remarks/>
        Public Event ValidateCompleted As ValidateCompletedEventHandler
        
        '''<remarks/>
        Public Event PingCompleted As PingCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ServiceCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/Create", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Create(ByVal post As GalleryPost) As Boolean
            Dim results() As Object = Me.Invoke("Create", New Object() {post})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal post As GalleryPost)
            Me.CreateAsync(post, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal post As GalleryPost, ByVal userState As Object)
            If (Me.CreateOperationCompleted Is Nothing) Then
                Me.CreateOperationCompleted = AddressOf Me.OnCreateOperationCompleted
            End If
            Me.InvokeAsync("Create", New Object() {post}, Me.CreateOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCompleted(Me, New CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ServiceCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/Update", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByVal post As GalleryPost)
            Me.Invoke("Update", New Object() {post})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal post As GalleryPost)
            Me.UpdateAsync(post, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal post As GalleryPost, ByVal userState As Object)
            If (Me.UpdateOperationCompleted Is Nothing) Then
                Me.UpdateOperationCompleted = AddressOf Me.OnUpdateOperationCompleted
            End If
            Me.InvokeAsync("Update", New Object() {post}, Me.UpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ServiceCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/Delete", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Delete(ByVal postID As Integer)
            Me.Invoke("Delete", New Object() {postID})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal postID As Integer)
            Me.DeleteAsync(postID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal postID As Integer, ByVal userState As Object)
            If (Me.DeleteOperationCompleted Is Nothing) Then
                Me.DeleteOperationCompleted = AddressOf Me.OnDeleteOperationCompleted
            End If
            Me.InvokeAsync("Delete", New Object() {postID}, Me.DeleteOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ServiceCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/GetCategories", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCategories() As String()
            Dim results() As Object = Me.Invoke("GetCategories", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCategoriesAsync()
            Me.GetCategoriesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCategoriesAsync(ByVal userState As Object)
            If (Me.GetCategoriesOperationCompleted Is Nothing) Then
                Me.GetCategoriesOperationCompleted = AddressOf Me.OnGetCategoriesOperationCompleted
            End If
            Me.InvokeAsync("GetCategories", New Object(-1) {}, Me.GetCategoriesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCategoriesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCategoriesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCategoriesCompleted(Me, New GetCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ServiceCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/GetAlbumHeirarchy", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAlbumHeirarchy() As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> Album()
            Dim results() As Object = Me.Invoke("GetAlbumHeirarchy", New Object(-1) {})
            Return CType(results(0),Album())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAlbumHeirarchyAsync()
            Me.GetAlbumHeirarchyAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAlbumHeirarchyAsync(ByVal userState As Object)
            If (Me.GetAlbumHeirarchyOperationCompleted Is Nothing) Then
                Me.GetAlbumHeirarchyOperationCompleted = AddressOf Me.OnGetAlbumHeirarchyOperationCompleted
            End If
            Me.InvokeAsync("GetAlbumHeirarchy", New Object(-1) {}, Me.GetAlbumHeirarchyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAlbumHeirarchyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAlbumHeirarchyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAlbumHeirarchyCompleted(Me, New GetAlbumHeirarchyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ServiceCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/Galleries", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Galleries() As String()
            Dim results() As Object = Me.Invoke("Galleries", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GalleriesAsync()
            Me.GalleriesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GalleriesAsync(ByVal userState As Object)
            If (Me.GalleriesOperationCompleted Is Nothing) Then
                Me.GalleriesOperationCompleted = AddressOf Me.OnGalleriesOperationCompleted
            End If
            Me.InvokeAsync("Galleries", New Object(-1) {}, Me.GalleriesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGalleriesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GalleriesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GalleriesCompleted(Me, New GalleriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ServiceCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/GetPictures", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPictures() As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> GalleryPost()
            Dim results() As Object = Me.Invoke("GetPictures", New Object(-1) {})
            Return CType(results(0),GalleryPost())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPicturesAsync()
            Me.GetPicturesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPicturesAsync(ByVal userState As Object)
            If (Me.GetPicturesOperationCompleted Is Nothing) Then
                Me.GetPicturesOperationCompleted = AddressOf Me.OnGetPicturesOperationCompleted
            End If
            Me.InvokeAsync("GetPictures", New Object(-1) {}, Me.GetPicturesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPicturesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPicturesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPicturesCompleted(Me, New GetPicturesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ServiceCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/GetPicture", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPicture(ByVal pictureID As Integer) As GalleryPost
            Dim results() As Object = Me.Invoke("GetPicture", New Object() {pictureID})
            Return CType(results(0),GalleryPost)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPictureAsync(ByVal pictureID As Integer)
            Me.GetPictureAsync(pictureID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPictureAsync(ByVal pictureID As Integer, ByVal userState As Object)
            If (Me.GetPictureOperationCompleted Is Nothing) Then
                Me.GetPictureOperationCompleted = AddressOf Me.OnGetPictureOperationCompleted
            End If
            Me.InvokeAsync("GetPicture", New Object() {pictureID}, Me.GetPictureOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPictureOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPictureCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPictureCompleted(Me, New GetPictureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ServiceCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/GetAlbumPictures", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAlbumPictures(ByVal albumID As Integer) As <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> GalleryPost()
            Dim results() As Object = Me.Invoke("GetAlbumPictures", New Object() {albumID})
            Return CType(results(0),GalleryPost())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAlbumPicturesAsync(ByVal albumID As Integer)
            Me.GetAlbumPicturesAsync(albumID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAlbumPicturesAsync(ByVal albumID As Integer, ByVal userState As Object)
            If (Me.GetAlbumPicturesOperationCompleted Is Nothing) Then
                Me.GetAlbumPicturesOperationCompleted = AddressOf Me.OnGetAlbumPicturesOperationCompleted
            End If
            Me.InvokeAsync("GetAlbumPictures", New Object() {albumID}, Me.GetAlbumPicturesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAlbumPicturesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAlbumPicturesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAlbumPicturesCompleted(Me, New GetAlbumPicturesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/GetSupportedExtensions", RequestElementName:="GetSupportedExtensions", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseElementName:="GetSupportedExtensionsResponse", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSupportedFileExtensions() As <System.Xml.Serialization.XmlArrayAttribute("GetSupportedExtensionsResult")> String()
            Dim results() As Object = Me.Invoke("GetSupportedFileExtensions", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSupportedFileExtensionsAsync()
            Me.GetSupportedFileExtensionsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSupportedFileExtensionsAsync(ByVal userState As Object)
            If (Me.GetSupportedFileExtensionsOperationCompleted Is Nothing) Then
                Me.GetSupportedFileExtensionsOperationCompleted = AddressOf Me.OnGetSupportedFileExtensionsOperationCompleted
            End If
            Me.InvokeAsync("GetSupportedFileExtensions", New Object(-1) {}, Me.GetSupportedFileExtensionsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSupportedFileExtensionsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSupportedFileExtensionsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSupportedFileExtensionsCompleted(Me, New GetSupportedFileExtensionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ServiceCredentialsValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/Validate", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Validate() As Boolean
            Dim results() As Object = Me.Invoke("Validate", New Object(-1) {})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ValidateAsync()
            Me.ValidateAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ValidateAsync(ByVal userState As Object)
            If (Me.ValidateOperationCompleted Is Nothing) Then
                Me.ValidateOperationCompleted = AddressOf Me.OnValidateOperationCompleted
            End If
            Me.InvokeAsync("Validate", New Object(-1) {}, Me.ValidateOperationCompleted, userState)
        End Sub
        
        Private Sub OnValidateOperationCompleted(ByVal arg As Object)
            If (Not (Me.ValidateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ValidateCompleted(Me, New ValidateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://communityserver.org/gallery/services/posts/Ping", RequestNamespace:="http://communityserver.org/gallery/services/posts/", ResponseNamespace:="http://communityserver.org/gallery/services/posts/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Ping()
            Me.Invoke("Ping", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PingAsync()
            Me.PingAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PingAsync(ByVal userState As Object)
            If (Me.PingOperationCompleted Is Nothing) Then
                Me.PingOperationCompleted = AddressOf Me.OnPingOperationCompleted
            End If
            Me.InvokeAsync("Ping", New Object(-1) {}, Me.PingOperationCompleted, userState)
        End Sub
        
        Private Sub OnPingOperationCompleted(ByVal arg As Object)
            If (Not (Me.PingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PingCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://communityserver.org/gallery/services/posts/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://communityserver.org/gallery/services/posts/", IsNullable:=false)>  _
    Partial Public Class ServiceCredentials
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private sectionNameField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SectionName() As String
            Get
                Return Me.sectionNameField
            End Get
            Set
                Me.sectionNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://communityserver.org/gallery/services/posts/")>  _
    Partial Public Class Album
        
        Private idField As Integer
        
        Private nameField As String
        
        Private photoCountField As Integer
        
        Private albumsField() As Album
        
        '''<remarks/>
        Public Property ID() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhotoCount() As Integer
            Get
                Return Me.photoCountField
            End Get
            Set
                Me.photoCountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Albums() As Album()
            Get
                Return Me.albumsField
            End Get
            Set
                Me.albumsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://communityserver.org/gallery/services/posts/")>  _
    Partial Public Class GalleryPost
        
        Private postIDField As Integer
        
        Private subjectField As String
        
        Private descriptionField As String
        
        Private filenameField As String
        
        Private contentTypeField As String
        
        Private fileSizeField As Long
        
        Private pictureDataField() As Byte
        
        Private categoriesField() As String
        
        '''<remarks/>
        Public Property PostID() As Integer
            Get
                Return Me.postIDField
            End Get
            Set
                Me.postIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Subject() As String
            Get
                Return Me.subjectField
            End Get
            Set
                Me.subjectField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Filename() As String
            Get
                Return Me.filenameField
            End Get
            Set
                Me.filenameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContentType() As String
            Get
                Return Me.contentTypeField
            End Get
            Set
                Me.contentTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FileSize() As Long
            Get
                Return Me.fileSizeField
            End Get
            Set
                Me.fileSizeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property PictureData() As Byte()
            Get
                Return Me.pictureDataField
            End Get
            Set
                Me.pictureDataField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Categories() As String()
            Get
                Return Me.categoriesField
            End Get
            Set
                Me.categoriesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub CreateCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub UpdateCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub DeleteCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub GetCategoriesCompletedEventHandler(ByVal sender As Object, ByVal e As GetCategoriesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCategoriesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub GetAlbumHeirarchyCompletedEventHandler(ByVal sender As Object, ByVal e As GetAlbumHeirarchyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAlbumHeirarchyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Album()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Album())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub GalleriesCompletedEventHandler(ByVal sender As Object, ByVal e As GalleriesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GalleriesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub GetPicturesCompletedEventHandler(ByVal sender As Object, ByVal e As GetPicturesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPicturesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GalleryPost()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GalleryPost())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub GetPictureCompletedEventHandler(ByVal sender As Object, ByVal e As GetPictureCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPictureCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GalleryPost
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GalleryPost)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub GetAlbumPicturesCompletedEventHandler(ByVal sender As Object, ByVal e As GetAlbumPicturesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAlbumPicturesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GalleryPost()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GalleryPost())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub GetSupportedFileExtensionsCompletedEventHandler(ByVal sender As Object, ByVal e As GetSupportedFileExtensionsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSupportedFileExtensionsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub ValidateCompletedEventHandler(ByVal sender As Object, ByVal e As ValidateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ValidateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub PingCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
